name: zip_python_packages_on_deploy

on:
  push:
    branches:
      - main
      
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Remove sendtext_lambda_layers.zip
        uses: JesseTG/rm@v1.0.3
        with:
          path: /terraform/sendtext_lambda_layers.zip
      - name: Remove sendtext_lambda_function.zip
        uses: JesseTG/rm@v1.0.3
        with:
          path: /terraform/sendtext_lambda_function.zip
          
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output sendtext_lambda_layers.zip
        run: zip -qq -r ../terraform/sendtext_lambda_layers.zip ./python
        working-directory: /lambda/
      - name: sendtext_lambda_function.zip
        run: zip -qq -r ../terraform/sendtext_lambda_function.zip ./lambda_function.py
        working-directory: /lambda/