name: zip_python_packages_on_deploy

on:
  push:
    branches:
      - main
      
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sendtext_lambda_layers.zip /lambda/python
      - name: rm old zip files
        run: |
          cd ./tu6-messaging-service/terraform
          rm sendtext_lambda_layers.zip
          rm sendtext_lambda_function.zip
      - name: Zip Python Layers Module Library
        run: |
          cd ./tu6-messaging-service/lambda
          zip ./tu6-messaging-service/terraform/sendtext_lambda_layers.zip ./python -r
      - name: Zip Python Function
        run: |
          cd ./lambda
          zip ../terraform/sendtest_lambda_function.zip lambda_function.py
      
